name: RubyStackNews Events Bot

on:
  schedule:
    - cron: "0 9 * * *"
  pull_request:
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest
    environment: demo

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgd-dev

      - name: Install gems
        run: gem install ruby-libgd x

      - run: bundle install

      - run: ruby demo/rsn_events_bot/social_event_image.rb

      - run: ruby demo/rsn_events_bot/post_to_x.rb
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
