name: RubyStackNews Bot

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bot:
    runs-on: ubuntu-latest
    environment: demo

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - run: sudo apt-get update && sudo apt-get install -y libgd-dev

      - run: gem install ruby-libgd x

      - run: ruby demo/rsn_events_bot/social_event_image.rb

      - name: Commit image
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "rsn-bot"
          git config --global user.email "bot@rubystacknews.com"

          git add demo/rsn_events_bot/rsn_events.png
          git commit -m "update events image" || echo "no changes"
          git push

      - run: ruby demo/rsn_events_bot/post_to_mastodon.rb
        env:
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          MASTODON_INSTANCE: https://ruby.social